export const COUNTRY_TO_LANG: { [key: string]: string } = {
    'US': 'en', 'GB': 'en', 'AU': 'en', 'CA': 'en', 'NZ': 'en',
    'ES': 'es', 'MX': 'es', 'AR': 'es', 'CO': 'es',
    'FR': 'fr', 'BE': 'fr',
    'DE': 'de', 'AT': 'de', 'CH': 'de',
    'IT': 'it',
    'PT': 'pt', 'BR': 'pt',
    'RU': 'ru', 'UA': 'uk',
    'CN': 'zh', 'HK': 'zh', 'TW': 'zh',
    'JP': 'ja',
    'KR': 'ko',
    'SA': 'ar', 'AE': 'ar', 'EG': 'ar',
    'IN': 'hi',
    'BD': 'bn',
    'PK': 'pa',
    'ID': 'jv',
    'TR': 'tr',
    'VN': 'vi',
    'TH': 'th',
    'PL': 'pl'
};

export const LANG_NAMES: { [key: string]: string } = {
    'en': 'English',
    'es': 'Español',
    'fr': 'Français',
    'de': 'Deutsch',
    'it': 'Italiano',
    'pt': 'Português',
    'ru': 'Русский',
    'zh': '中文',
    'ja': '日本語',
    'ko': '한국어',
    'ar': 'العربية',
    'hi': 'हिन्दी',
    'bn': 'বাংলা',
    'pa': 'ਪੰਜਾਬੀ',
    'jv': 'Javanese',
    'tr': 'Türkçe',
    'vi': 'Tiếng Việt',
    'th': 'ไทย',
    'pl': 'Polski',
    'uk': 'Українська'
};
